volumes:
  etebase_data:

services:
  etebase:
    image: victorrds/etesync
    container_name: "etebase"
    volumes:
      - etebase_data:/data:rw
    environment:
      DEBUG: true
      ALLOWED_HOSTS: "127.0.0.1"
      SERVER: http
      SUPER_USER: admin
      SUPER_PASS: admin
    restart: always
    ports:
      - "8000:3735"
